apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: arbeid-situasjon
  namespace: default
  labels:
    team: pto
spec:
  image: {{image}}
  port: 8080
  resources:
    limits:
      cpu: "3"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 512Mi
  liveness:
    path: arbeid/situasjon/internal/isAlive
    initialDelay: 20
  readiness:
    path: arbeid/situasjon/internal/selftest
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: arbeid/situasjon/internal/metrics
  ingresses:
    - https://www.nav.no/arbeid/situasjon
  vault:
    enabled: true
  webproxy: true
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
